config/routes.rb
Rails.application.routes.draw do
  root 'pictures#index'
  resources :pictures do
    collection do
      post :confirm
    end
  end
  resources :sessions
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
   validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }

  has_secure_password
  validates :password, length: { minimum: 6 }
  has_many :pictures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required

  private

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  def index
    @pictures = Picture.all
  end

  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    if params[:back]
      render :new
    else
      if @picture.save
        redirect_to pictures_path, notice: "作成しました！"
      else
        render :new
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    if @picture.update(picture_params)
      redirect_to pictures_path, notice: "編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_path, notice:"削除しました！"
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end


  private

  def picture_params
    params.require(:picture).permit(:image, :image_cache, :content)
  end

  def set_picture
  @picture = Picture.find(params[:id])
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,:password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tomodati</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if logged_in? %>
        <%= link_to "Profile", user_path(current_user.id) %>
        <%= link_to "Logout", session_path(current_user.id), method: :delete %>
      <% else %>
        <%= link_to "Sign up", new_user_path %>
        <%= link_to "Login", new_session_path %>
      <% end %>
    </header>
    
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true, url: choose_new_or_edit ) do |form| %>


<% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="picture_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div class="picture_image">
    <%= form.label :image %>
    <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>
  <%= form.submit %>
<% end %>

<%= link_to "一覧画面にもどる", pictures_path %>

app/views/pictures/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @picture, local: true, url: pictures_path ) do |form| %>

  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>

  <p>コメント:<%= @picture.content %></p>
  <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
  <%= form.submit  "登録する" %>
<% end %>

<%= form_with(model:@picture, url:new_picture_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/pictures/edit.html.erb
<h2>編集する</h2>

<%= render 'form' %>

app/views/pictures/index.html.erb
<h1>投稿一覧</h1>

<table>
  <tr>
    <th>画像</th>
    <th>コメント</th>
    <th>ユーザー</th>
  </tr>

<% @pictures.each do |picture| %>
  <tr class="main">
    <td><%= image_tag(picture.image.url) if picture.image && picture.image.url %></td>
    <td><%= picture.content %></td>
    <td><%= picture.user.name %></td>

    <td><%= link_to '詳細を確認する', picture_path(picture.id) %></td>
    <td><%= link_to "編集する", edit_picture_path(picture.id) %></td>
    <td><%= link_to '削除する', picture_path(picture.id), method: :delete ,data: { confirm: '本当に削除していいですか？' }  %></td>
  </tr>
<% end %>
</table>

<footer>
  <%= link_to '新しく投稿する', new_picture_path ,class:"foot"%>
</footer>

app/views/pictures/new.html.erb
<h2>作成する</h2>

<%= render 'form' %>

app/views/pictures/show.html.erb
<h1>投稿詳細画面</h1>
<p>画像: <%= image_tag @picture.image.url %></p>
<p>内容: <%= @picture.content %></p>
<p>ユーザー: <%= @picture.user.name %></p>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>

<%= link_to "一覧画面に進む", pictures_path %>